gchq/koryphe

src/main/java/uk/gov/gchq/koryphe/impl/binaryoperator/And.java, src/main/java/uk/gov/gchq/koryphe/impl/binaryoperator/Or.java, src/test/java/uk/gov/gchq/koryphe/impl/binaryoperator/AndTest.java, src/test/java/uk/gov/gchq/koryphe/impl/binaryoperator/OrTest.java
Added "Or" function and unit test
=> gh-34 - Binary Operations

pom.xml, src/main/java/uk/gov/gchq/koryphe/impl/function/ToString.java, src/test/java/uk/gov/gchq/koryphe/impl/function/ToStringTest.java
Added ToString function and associated Unit Test
=> gh-36 - ToString Function

src/main/java/uk/gov/gchq/koryphe/impl/binaryoperator/And.java, src/main/java/uk/gov/gchq/koryphe/impl/binaryoperator/CollectionConcat.java, src/main/java/uk/gov/gchq/koryphe/impl/binaryoperator/First.java, src/main/java/uk/gov/gchq/koryphe/impl/binaryoperator/Max.java, src/main/java/uk/gov/gchq/koryphe/impl/binaryoperator/NumericAggregateFunction.java, src/main/java/uk/gov/gchq/koryphe/impl/binaryoperator/Or.java, src/main/java/uk/gov/gchq/koryphe/impl/binaryoperator/Product.java, src/main/java/uk/gov/gchq/koryphe/impl/binaryoperator/StringConcat.java, src/main/java/uk/gov/gchq/koryphe/impl/binaryoperator/StringDeduplicateConcat.java, src/main/java/uk/gov/gchq/koryphe/impl/binaryoperator/Sum.java, src/main/java/uk/gov/gchq/koryphe/impl/function/Concat.java
Corrected grammar in the Javadoc for a number of files, and also an incorrect code link.
=> gh-45 - Javadoc corrected

core/src/main/java/uk/gov/gchq/koryphe/impl/predicate/StringContains.java, core/src/test/java/uk/gov/gchq/koryphe/impl/predicate/StringContainsTest.java
StringContains predicate implemented - can be constructed with the String that is to be checked whether it contains the input. The input is passed in with the test(final String input) method.
=> gh-54 - StringContains implemented, unit tests written

core/src/main/java/uk/gov/gchq/koryphe/impl/function/ExtractKeys.java, core/src/main/java/uk/gov/gchq/koryphe/impl/function/ExtractValue.java, core/src/main/java/uk/gov/gchq/koryphe/impl/function/ExtractValues.java, core/src/test/java/uk/gov/gchq/koryphe/impl/function/ExtractKeysTest.java, core/src/test/java/uk/gov/gchq/koryphe/impl/function/ExtractValueTest.java, core/src/test/java/uk/gov/gchq/koryphe/impl/function/ExtractValuesTest.java, doc/src/main/java/uk/gov/gchq/koryphe/example/RunAll.java, doc/src/main/java/uk/gov/gchq/koryphe/example/function/ExtractValueExample.java
ExtractValue function added, with accompanying test and example class.
=> gh-74 - ExtractValue, test, example added

core/src/main/java/uk/gov/gchq/koryphe/impl/predicate/range/AbstractInTimeRange.java, core/src/main/java/uk/gov/gchq/koryphe/impl/predicate/range/AbstractInTimeRangeDual.java, core/src/main/java/uk/gov/gchq/koryphe/impl/predicate/range/InDateRange.java, core/src/main/java/uk/gov/gchq/koryphe/impl/predicate/range/InDateRangeDual.java, core/src/main/java/uk/gov/gchq/koryphe/impl/predicate/range/InRange.java, core/src/main/java/uk/gov/gchq/koryphe/impl/predicate/range/InRangeDual.java, core/src/main/java/uk/gov/gchq/koryphe/impl/predicate/range/InTimeRange.java, core/src/main/java/uk/gov/gchq/koryphe/impl/predicate/range/InTimeRangeDual.java, core/src/main/java/uk/gov/gchq/koryphe/util/DateUtil.java, core/src/main/java/uk/gov/gchq/koryphe/util/TimeUnit.java, core/src/test/java/uk/gov/gchq/koryphe/impl/predicate/range/InTimeRangeDualTest.java, core/src/test/java/uk/gov/gchq/koryphe/impl/predicate/range/InTimeRangeTest.java, core/src/test/java/uk/gov/gchq/koryphe/util/DateUtilTest.java
gh-78 - added milliseconds to date format
=> gh-77 - added time unit

core/src/main/java/uk/gov/gchq/koryphe/impl/function/Length.java, core/src/main/java/uk/gov/gchq/koryphe/impl/predicate/IsShorterThan.java, core/src/test/java/uk/gov/gchq/koryphe/impl/function/LengthTest.java, doc/src/main/java/uk/gov/gchq/koryphe/example/function/LengthExample.java
Added Length function, tests and example.
Modified IsShorterThan to delegate to Length.
=> gh-85 - Length function, test and example

pom.xml
Tested locally with Maven 3.6.3.
=> gh-175 - Updated findbugs plugin version for Maven 3.6.x.

core/src/main/java/uk/gov/gchq/koryphe/signature/Signature.java, core/src/test/java/uk/gov/gchq/koryphe/impl/function/MapToTupleTest.java, core/src/test/java/uk/gov/gchq/koryphe/signature/SignatureTest.java
…pleSignature for TupleN implementations.
=> gh-184 Improve signature generation

core/src/main/java/uk/gov/gchq/koryphe/impl/function/ToLowerCase.java, core/src/main/java/uk/gov/gchq/koryphe/impl/function/ToUpperCase.java, core/src/test/java/uk/gov/gchq/koryphe/impl/function/ToLowerCaseTest.java, core/src/test/java/uk/gov/gchq/koryphe/impl/function/ToUpperCaseTest.java
Return values when input is a String. Extended tests to check both routes through the functions - when the input is a String and when the input is some other Object (with a suitable toString() implementation).
=> gh-189 - Return values from ToUpper and ToLower when input is a String.

core/src/main/java/uk/gov/gchq/koryphe/impl/function/StringTruncate.java, core/src/test/java/uk/gov/gchq/koryphe/impl/function/StringTruncateTest.java
=> gh-201 fix truncate error

core/src/main/java/uk/gov/gchq/koryphe/serialisation/json/SimpleClassNameIdResolver.java, pom.xml
=> Gh 125 update jackson

core/src/main/java/uk/gov/gchq/koryphe/impl/function/ParseDate.java, core/src/main/java/uk/gov/gchq/koryphe/util/DateUtil.java, core/src/test/java/uk/gov/gchq/koryphe/impl/function/ParseDateTest.java
=> gh-149: Added @hj325488's work and extra test

.github/workflows/release.yaml, pom.xml
=> Gh-241: Fix Javadoc build failure and missing navigation frames

pom.xml
=> Gh-248: Replace Log4J with Reload4J

.github/workflows/release.yaml
=> gh-254: Fix generate javadoc in release

core/src/main/java/uk/gov/gchq/koryphe/impl/function/ToFloat.java, core/src/test/java/uk/gov/gchq/koryphe/impl/function/ToFloatTest.java
This is a missing koryphe function required by gh-2558-openCypherCSV. Takes an object and converts it into a Float
- Resolve #257
=> gh-257 added ToFloat function

core/src/main/java/uk/gov/gchq/koryphe/iterable/ChainedIterator.java, core/src/test/java/uk/gov/gchq/koryphe/iterable/ChainedIterableTest.java
=> gh-272 ChainedIterator.getIterator NullPointer Exception.

core/src/main/java/uk/gov/gchq/koryphe/iterable/LimitedIterator.java, core/src/test/java/uk/gov/gchq/koryphe/iterable/LimitedIterableTest.java, core/src/test/java/uk/gov/gchq/koryphe/util/IterableUtilTest.java
=> gh-278: Changed LimitedIterator exception to RuntimeException

README.md
=> Update crown copyright link

.github/workflows/continuous-integration.yaml
=> gh-287: Run CI and upload coverage on develop

core/src/test/java/uk/gov/gchq/koryphe/binaryoperator/AdaptedBinaryOperatorTest.java, core/src/test/java/uk/gov/gchq/koryphe/impl/function/ToSetTest.java
=> Gh-289: Typos in ToSetTest and AdaptedBinaryOperatorTest

code-style/spotbugs-exclude.xml, pom.xml
=> Gh-303: Update Spotbugs

pom.xml
=> Gh-310: Improve JUnit tests to run in parallel

.github/workflows/continuous-integration.yaml, cd/after_success.sh
=> Gh-314: Update codecov

.github/release-notes.yml, .github/workflows/continuous-integration.yaml, .github/workflows/create-hotfix-branch.yaml, .github/workflows/create-release-branch.yaml, .github/workflows/link-issue.yml, .github/workflows/release-standalone.yaml, .github/workflows/release.yaml
=> Gh 307: Upgrade workflows
